version: '3.8'

services:
  # Servicio de la API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neural-image-api
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - ./uploads:/usr/src/app/uploads
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      - MONGODB_URI=mongodb://${MONGO_USER:-user}:${MONGO_PASSWORD:-password}@mongodb:27017/${MONGO_DB:-neural_image_db}?authSource=admin
    depends_on:
      - mongodb
    networks:
      - neural-network

  # Servicio de base de datos MongoDB
  mongodb:
    image: mongo:latest
    container_name: neural-image-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-user}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${MONGO_DB:-neural_image_db}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "${MONGO_PORT:-27017}:27017"
    networks:
      - neural-network

# Volúmenes para persistencia de datos
volumes:
  mongodb_data:
    driver: local

# Red para comunicación entre servicios
networks:
  neural-network:
    driver: bridge
